### ISSUE TITLE
Image loading is slow when there are a large number of images in offline mode

### ISSUE THREAD

**Issue by tackme31** [meganz/android#187]
## General Information

- **MEGA Version:** 
6.6 (433)

- **OS Version(s):** 
Android 12

- **Devices/Simulators:** 
Pixel 5

- **Reproducible? (Yes/No):** 
Yes

##  What happened?
A large number of image files in the same hierarchy in Offline mode slows down image loading.

### how to reproduce
1. Upload about 150 image files on the same level of a folder.
2. Check "Available Offline" for all those images.
3. Open one of the downloaded images in offline mode

On my device it took 8 seconds to open the image.

## What did you expect to happen?
The image can be opened instantly.

**Comment by javiergm1983** [comment]
Hi, we have already fixed this issue in v6.7 which will be available in the following days. Please check it again once you receive that update. Thanks.

**Comment by javiergm1983** [comment]
Hi @tackme31 we have started today the live roll out of the v6.7 which contains a fix for your issue.
Please, could you confirm here that the issue is solved when you receive that update? Thanks.

**Comment by tackme31** [comment]
Thank you for your kind support. I will respond again as soon as we confirm.

**Comment by tackme31** [comment]
Hi. I have received the latest update, but this issue does not seem to have been resolved. 
To confirm, I tried the following steps.

- Delete the cache and then preview the image and it still takes long time (35sec / 280images).
- Preview again the same image (with cache) and it does not affect loading time.
- Preview an image in a folder with fewer images, the image is loaded quickly.

Thank you.

**Comment by javiergm1983** [comment]
@Gnzlt please could you take a look? Thanks.

**Comment by javiergm1983** [comment]
Hi @tackme31, a new approach has been included in the v6.9, so I hope it finally solves your problem. Please let us to know once you receive that update. Thanks.

**Comment by tackme31** [comment]
@javiergm1983 
Sorry for the delay in replying.
I received version 6.10 and rechecked this issue, but it has not been resolved. Below is the version information at the time of confirmation.

- App version: 6.10.1
- Android version: 12

For reference, the time taken to load is listed below. It appears to be roughly proportional to the number of files.

- 67 images / 13sec.
- 100 images / 21 sec.
- 300 images / 66 sec.

If there is any operation you would like me to try or any information you need, please let me know.
Thank you.

**Comment by Gnzlt** [comment]
Hi @tackme31, could you please confirm that it still happens after the first load when offline images are cached?
Thanks

**Comment by tackme31** [comment]
@Gnzlt 
I confirmed that there was no change in loading time before and after caching.
I then tried with the cache removed from the settings just to be sure, but the result was the same.

**Comment by DevMehta1206** [comment]
@tackme31 @javiergm1983 @Gnzlt Hello Guys i am new here and intrested in contribution in this repo can anyone please help me in setting up project. i am getting some errors while setting it up.
